import { Deal } from "./types";

export const seedDeals: Deal[] = [
  {
    id: "d1",
    title: "Enterprise Suite",
    company: "Globex Corp",
    owner: "Anish",
    value: 92000,
    stage: "New",
    probability: 20,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    tags: ["priority", "enterprise"],
  },
  {
    id: "d2",
    title: "Pro Annual",
    company: "Initech",
    owner: "Sam",
    value: 18000,
    stage: "Qualified",
    probability: 45,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
    tags: ["trial"],
  },
  {
    id: "d3",
    title: "Team Starter",
    company: "Hooli",
    owner: "Priya",
    value: 6500,
    stage: "Negotiation",
    probability: 60,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
    tags: ["discount"],
  },
  {
    id: "d4",
    title: "Platform Upgrade",
    company: "Acme Inc",
    owner: "Anish",
    value: 32000,
    stage: "New",
    probability: 30,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    tags: ["upsell"],
  },
  {
    id: "d5",
    title: "Security Add-on",
    company: "Umbrella Co",
    owner: "Lee",
    value: 12000,
    stage: "Lost",
    probability: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
    tags: ["security"],
  },
];
